/*
# Offer System — Tables, RLS, and Core Functions

## Overview
Adds a complete offer/survey/app-install earning system integrated into the existing
GoldClicks PTC platform. This migration creates the database schema, RLS policies,
and SECURITY DEFINER RPC functions for offer tracking, conversion crediting,
reversals, and admin management.

## New Tables

### offer_providers
Stores configuration for third-party offer/survey/app providers.
- id (uuid PK)
- slug (text, unique) — e.g. 'adgem', 'offertoro', 'cpx_research'
- display_name (text)
- provider_type (text) — 'survey' | 'app_install' | 'offerwall' | 'game'
- enabled (boolean, default false)
- api_key_encrypted (text) — server-side only, never exposed to client
- postback_secret_encrypted (text) — server-side only
- publisher_id (text) — publisher/affiliate ID for tracking URL generation
- postback_url (text) — the URL providers should call (informational; the actual
  edge function URL is fixed per project)
- currency_code (text, default 'USD')
- reward_margin_percent (numeric, default 100) — percent of provider reward passed to user
- config (jsonb) — provider-specific configuration (tracking domains, sub IDs, etc.)
- created_at, updated_at (timestamptz)

### offers
Catalog of available offers from providers. Populated by provider API or admin.
- id (uuid PK)
- provider_id (uuid FK → offer_providers, CASCADE)
- provider_offer_id (text) — the offer's ID at the provider
- title, description, requirements (text)
- offer_type (text) — 'survey' | 'app_install' | 'game' | 'signup' | 'trial' | 'other'
- reward (numeric(18,8)) — reward amount in platform currency
- currency_code (text, default 'USD')
- icon_url (text)
- destination_url (text) — provider tracking URL template
- platform (text) — 'android' | 'ios' | 'web' | 'all'
- estimated_time_minutes (integer)
- difficulty (text) — 'easy' | 'medium' | 'hard'
- category (text)
- active (boolean, default true)
- start_date, end_date (timestamptz, nullable)
- created_at, updated_at (timestamptz)
- UNIQUE(provider_id, provider_offer_id)

### offer_sessions
Tracks every offer click/start by a user. One row per click.
- id (uuid PK)
- user_id (uuid FK → auth.users, CASCADE)
- offer_id (uuid FK → offers, SET NULL — keep session even if offer deleted)
- provider_id (uuid FK → offer_providers, CASCADE)
- provider_slug (text) — denormalized for quick lookups in webhooks
- provider_offer_id (text) — denormalized
- offer_type (text) — denormalized
- tracking_id (text, unique) — generated by the platform, sent to provider as sub_id/click_id
- click_id (text) — provider's click ID if returned
- status (text) — 'clicked' | 'started' | 'pending' | 'completed' | 'rejected' | 'reversed' | 'expired'
- reward (numeric(18,8)) — snapshot of reward at click time
- currency_code (text)
- provider_conversion_id (text) — set on conversion, unique for idempotency
- revenue (numeric(18,8)) — provider-side revenue if supplied
- metadata (jsonb) — extra provider data
- expires_at (timestamptz) — session expiry
- created_at, completed_at, reversed_at (timestamptz)
- Indexes on (user_id, created_at), (tracking_id), (provider_conversion_id), (provider_slug, status)

### offer_conversions
Immutable audit trail of every conversion/reversal event from providers.
- id (uuid PK)
- session_id (uuid FK → offer_sessions, CASCADE)
- user_id (uuid FK → auth.users, CASCADE)
- provider_id (uuid FK → offer_providers, CASCADE)
- provider_conversion_id (text) — provider's transaction ID
- event_type (text) — 'conversion' | 'reversal'
- reward (numeric(18,8))
- revenue (numeric(18,8))
- status (text) — 'processed' | 'duplicate' | 'rejected'
- raw_payload (jsonb) — full provider postback data for audit
- created_at (timestamptz)
- UNIQUE(provider_id, provider_conversion_id, event_type)

## RPC Functions (all SECURITY DEFINER)

### offer_start_session(p_offer_id uuid)
Called when user clicks Start on an offer. Creates an offer_session with status='clicked',
generates a unique tracking_id, and returns it along with the provider tracking URL.
Only works for active, enabled-provider offers. User must have status='active'.

### offer_list_available(p_offer_type text, p_platform text)
Returns available offers (active, enabled provider, within date range) with provider info.
Filters by offer_type ('all' for no filter) and platform ('all' for no filter).

### offer_list_my_sessions(p_status text, p_limit int, p_offset int)
Returns the authenticated user's offer sessions with offer title/provider info.
Filters by status ('all' for no filter).

### offer_get_session(p_session_id uuid)
Returns details for a single offer session owned by the caller.

### offer_process_conversion(
  p_provider_slug text, p_tracking_id text, p_conversion_id text,
  p_reward numeric, p_revenue numeric, p_event_type text, p_raw jsonb
)
Called ONLY by the offer-webhook edge function (service role). This is the
authoritative credit/reversal path:
1. Validates the provider exists and is enabled.
2. Finds the session by tracking_id.
3. Checks for duplicate conversion_id (idempotency).
4. For 'conversion': marks session completed, credits available_balance + total_earned,
   inserts ledger transaction with unique reference 'offer:<session_id>'.
5. For 'reversal': marks session reversed, debits the balance, inserts reversal ledger entry.
6. Records every event in offer_conversions (even duplicates, marked 'duplicate').

### offer_admin_stats()
Returns aggregate offer statistics for admin dashboard.

### offer_admin_list_sessions(
  p_provider_slug text, p_offer_type text, p_status text,
  p_user_id uuid, p_limit int, p_offset int
)
Returns all offer sessions with user info for admin management. Admin-only.

### offer_admin_list_providers()
Returns all provider configurations for admin. Does NOT expose encrypted secrets.
Admin-only.

### offer_admin_update_provider(
  p_provider_id uuid, p_enabled boolean, p_display_name text,
  p_publisher_id text, p_reward_margin_percent numeric, p_config jsonb
)
Updates non-secret provider configuration. Admin-only.

### offer_admin_set_provider_secret(
  p_provider_id uuid, p_secret_type text, p_secret_value text
)
Sets encrypted API key or postback secret. Admin-only. Secret is encrypted with
pgp_sym_encrypt using a server-side key.

## Security

- RLS enabled on all tables.
- Users can only SELECT their own offer_sessions and offer_conversions.
- Users can SELECT active offers and enabled providers (no secrets exposed).
- Users CANNOT INSERT/UPDATE/DELETE offers, providers, or conversions.
- offer_start_session is the only user-writable path (via RPC), and it only creates sessions.
- offer_process_conversion has NO grants to anon/authenticated — only the service role
  (edge function) can call it. This is enforced by REVOKE EXECUTE FROM PUBLIC and
  not granting to anon/authenticated.
- All admin functions check is_admin() internally.
- Provider secrets are encrypted at rest and never returned to any client.
- The transactions ledger is reused — offer rewards use type='offer_reward' with
  reference='offer:<session_id>' for idempotency.

## Important Notes
1. The existing transactions table gains two new type values: 'offer_reward' and 'offer_reversal'.
   The CHECK constraint on transactions.type is dropped and recreated to include these.
2. The existing profiles table is NOT modified — offer rewards update the same
   available_balance and total_earned columns using the same SECURITY DEFINER pattern.
3. No second balance system is created.
4. All money movement uses FOR UPDATE locking on profiles, same as ptc_claim.
5. Provider secrets use pgp_sym_encrypt — requires pgcrypto extension (already enabled
   in the existing database if not, it's added here with CREATE EXTENSION IF NOT EXISTS).
*/

-- pgcrypto for encryption functions
CREATE EXTENSION IF NOT EXISTS pgcrypto;

-- =============================================================
-- TABLE: offer_providers
-- =============================================================
CREATE TABLE IF NOT EXISTS offer_providers (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  slug text UNIQUE NOT NULL,
  display_name text NOT NULL,
  provider_type text NOT NULL CHECK (provider_type IN ('survey', 'app_install', 'offerwall', 'game')),
  enabled boolean NOT NULL DEFAULT false,
  api_key_encrypted text,
  postback_secret_encrypted text,
  publisher_id text DEFAULT '',
  postback_url text DEFAULT '',
  currency_code text NOT NULL DEFAULT 'USD',
  reward_margin_percent numeric(5,2) NOT NULL DEFAULT 100.00,
  config jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

ALTER TABLE offer_providers ENABLE ROW LEVEL SECURITY;

-- Users can see enabled providers (no secrets)
DROP POLICY IF EXISTS "select_enabled_providers" ON offer_providers;
CREATE POLICY "select_enabled_providers"
  ON offer_providers FOR SELECT
  TO authenticated
  USING (enabled = true);

-- No INSERT/UPDATE/DELETE policies for users on providers — admin only via RPC

-- =============================================================
-- TABLE: offers
-- =============================================================
CREATE TABLE IF NOT EXISTS offers (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  provider_id uuid NOT NULL REFERENCES offer_providers(id) ON DELETE CASCADE,
  provider_offer_id text NOT NULL,
  title text NOT NULL,
  description text DEFAULT '',
  requirements text DEFAULT '',
  offer_type text NOT NULL CHECK (offer_type IN ('survey', 'app_install', 'game', 'signup', 'trial', 'other')),
  reward numeric(18,8) NOT NULL DEFAULT 0,
  currency_code text NOT NULL DEFAULT 'USD',
  icon_url text DEFAULT '',
  destination_url text DEFAULT '',
  platform text NOT NULL DEFAULT 'all' CHECK (platform IN ('android', 'ios', 'web', 'all')),
  estimated_time_minutes integer DEFAULT 0,
  difficulty text DEFAULT 'easy' CHECK (difficulty IN ('easy', 'medium', 'hard')),
  category text DEFAULT '',
  active boolean NOT NULL DEFAULT true,
  start_date timestamptz,
  end_date timestamptz,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE(provider_id, provider_offer_id)
);

ALTER TABLE offers ENABLE ROW LEVEL SECURITY;

-- Users can see active offers from enabled providers
DROP POLICY IF EXISTS "select_active_offers" ON offers;
CREATE POLICY "select_active_offers"
  ON offers FOR SELECT
  TO authenticated
  USING (
    active = true
    AND EXISTS (
      SELECT 1 FROM offer_providers
      WHERE offer_providers.id = offers.provider_id
      AND offer_providers.enabled = true
    )
  );

-- =============================================================
-- TABLE: offer_sessions
-- =============================================================
CREATE TABLE IF NOT EXISTS offer_sessions (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  offer_id uuid REFERENCES offers(id) ON DELETE SET NULL,
  provider_id uuid NOT NULL REFERENCES offer_providers(id) ON DELETE CASCADE,
  provider_slug text NOT NULL DEFAULT '',
  provider_offer_id text NOT NULL DEFAULT '',
  offer_type text NOT NULL DEFAULT 'other',
  tracking_id text UNIQUE NOT NULL DEFAULT gen_random_uuid()::text,
  click_id text,
  status text NOT NULL DEFAULT 'clicked' CHECK (status IN ('clicked','started','pending','completed','rejected','reversed','expired')),
  reward numeric(18,8) NOT NULL DEFAULT 0,
  currency_code text NOT NULL DEFAULT 'USD',
  provider_conversion_id text,
  revenue numeric(18,8) DEFAULT 0,
  metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
  expires_at timestamptz DEFAULT now() + interval '24 hours',
  created_at timestamptz NOT NULL DEFAULT now(),
  completed_at timestamptz,
  reversed_at timestamptz
);

CREATE INDEX IF NOT EXISTS idx_offer_sessions_user_created
  ON offer_sessions(user_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_offer_sessions_tracking
  ON offer_sessions(tracking_id);
CREATE INDEX IF NOT EXISTS idx_offer_sessions_conversion
  ON offer_sessions(provider_conversion_id);
CREATE INDEX IF NOT EXISTS idx_offer_sessions_provider_status
  ON offer_sessions(provider_slug, status);

ALTER TABLE offer_sessions ENABLE ROW LEVEL SECURITY;

-- Users can see only their own sessions
DROP POLICY IF EXISTS "select_own_offer_sessions" ON offer_sessions;
CREATE POLICY "select_own_offer_sessions"
  ON offer_sessions FOR SELECT
  TO authenticated
  USING (auth.uid() = user_id);

-- No INSERT/UPDATE/DELETE policies — all via RPC functions

-- =============================================================
-- TABLE: offer_conversions
-- =============================================================
CREATE TABLE IF NOT EXISTS offer_conversions (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  session_id uuid NOT NULL REFERENCES offer_sessions(id) ON DELETE CASCADE,
  user_id uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  provider_id uuid NOT NULL REFERENCES offer_providers(id) ON DELETE CASCADE,
  provider_conversion_id text,
  event_type text NOT NULL CHECK (event_type IN ('conversion', 'reversal')),
  reward numeric(18,8) NOT NULL DEFAULT 0,
  revenue numeric(18,8) DEFAULT 0,
  status text NOT NULL DEFAULT 'processed' CHECK (status IN ('processed', 'duplicate', 'rejected')),
  raw_payload jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE(provider_id, provider_conversion_id, event_type)
);

CREATE INDEX IF NOT EXISTS idx_offer_conversions_session
  ON offer_conversions(session_id);
CREATE INDEX IF NOT EXISTS idx_offer_conversions_user
  ON offer_conversions(user_id, created_at DESC);

ALTER TABLE offer_conversions ENABLE ROW LEVEL SECURITY;

-- Users can see only their own conversion records
DROP POLICY IF EXISTS "select_own_offer_conversions" ON offer_conversions;
CREATE POLICY "select_own_offer_conversions"
  ON offer_conversions FOR SELECT
  TO authenticated
  USING (auth.uid() = user_id);

-- No INSERT/UPDATE/DELETE policies — all via RPC

-- =============================================================
-- Update transactions type constraint to include offer types
-- =============================================================
DO $$
BEGIN
  -- Drop old constraint if it exists
  IF EXISTS (
    SELECT 1 FROM information_schema.table_constraints
    WHERE table_name = 'transactions' AND constraint_name = 'transactions_type_check'
  ) THEN
    ALTER TABLE transactions DROP CONSTRAINT transactions_type_check;
  END IF;
END $$;

ALTER TABLE transactions ADD CONSTRAINT transactions_type_check
  CHECK (type IN (
    'ptc_reward', 'task_reward', 'referral_reward', 'deposit', 'withdrawal',
    'withdrawal_refund', 'adjustment', 'ad_transfer', 'ad_spend', 'ad_refund',
    'offer_reward', 'offer_reversal'
  ));

-- =============================================================
-- FUNCTION: offer_start_session (user-facing)
-- =============================================================
CREATE OR REPLACE FUNCTION offer_start_session(p_offer_id uuid)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_user uuid := auth.uid();
  v_profile profiles%ROWTYPE;
  v_offer offers%ROWTYPE;
  v_provider offer_providers%ROWTYPE;
  v_session offer_sessions%ROWTYPE;
  v_tracking_id text;
  v_tracking_url text;
BEGIN
  IF v_user IS NULL THEN
    RETURN jsonb_build_object('error', 'Not authenticated');
  END IF;

  SELECT * INTO v_profile FROM profiles WHERE id = v_user FOR UPDATE;
  IF NOT FOUND THEN
    RETURN jsonb_build_object('error', 'Profile not found');
  END IF;
  IF v_profile.status != 'active' THEN
    RETURN jsonb_build_object('error', 'Account is not active');
  END IF;

  SELECT * INTO v_offer FROM offers WHERE id = p_offer_id AND active = true FOR UPDATE;
  IF NOT FOUND THEN
    RETURN jsonb_build_object('error', 'Offer not available');
  END IF;

  SELECT * INTO v_provider FROM offer_providers WHERE id = v_offer.provider_id AND enabled = true FOR UPDATE;
  IF NOT FOUND THEN
    RETURN jsonb_build_object('error', 'Provider not available');
  END IF;

  -- Check date validity
  IF v_offer.start_date IS NOT NULL AND now() < v_offer.start_date THEN
    RETURN jsonb_build_object('error', 'Offer not yet available');
  END IF;
  IF v_offer.end_date IS NOT NULL AND now() > v_offer.end_date THEN
    RETURN jsonb_build_object('error', 'Offer has expired');
  END IF;

  -- Generate tracking ID
  v_tracking_id := encode(gen_random_bytes(16), 'hex');

  -- Insert session
  INSERT INTO offer_sessions (
    user_id, offer_id, provider_id, provider_slug, provider_offer_id,
    offer_type, tracking_id, status, reward, currency_code, expires_at
  ) VALUES (
    v_user, v_offer.id, v_provider.id, v_provider.slug, v_offer.provider_offer_id,
    v_offer.offer_type, v_tracking_id, 'clicked', v_offer.reward, v_offer.currency_code,
    now() + interval '24 hours'
  ) RETURNING * INTO v_session;

  -- Build tracking URL — replace placeholders in destination_url
  v_tracking_url := v_offer.destination_url;
  v_tracking_url := replace(v_tracking_url, '[SUB_ID]', v_tracking_id);
  v_tracking_url := replace(v_tracking_url, '[USER_ID]', v_user::text);
  v_tracking_url := replace(v_tracking_url, '[PUBLISHER_ID]', v_provider.publisher_id);
  v_tracking_url := replace(v_tracking_url, '[OFFER_ID]', v_offer.provider_offer_id);

  RETURN jsonb_build_object(
    'session_id', v_session.id,
    'tracking_id', v_tracking_id,
    'tracking_url', v_tracking_url,
    'reward', v_offer.reward,
    'currency', v_offer.currency_code,
    'offer_type', v_offer.offer_type,
    'title', v_offer.title
  );
END;
$$;

REVOKE EXECUTE ON FUNCTION offer_start_session(uuid) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION offer_start_session(uuid) TO authenticated;

-- =============================================================
-- FUNCTION: offer_list_available (user-facing)
-- =============================================================
CREATE OR REPLACE FUNCTION offer_list_available(
  p_offer_type text DEFAULT 'all',
  p_platform text DEFAULT 'all'
)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_user uuid := auth.uid();
BEGIN
  IF v_user IS NULL THEN
    RETURN '[]'::jsonb;
  END IF;

  RETURN COALESCE((
    SELECT jsonb_agg(jsonb_build_object(
      'id', o.id,
      'provider_id', o.provider_id,
      'provider_slug', p.slug,
      'provider_name', p.display_name,
      'provider_offer_id', o.provider_offer_id,
      'title', o.title,
      'description', o.description,
      'requirements', o.requirements,
      'offer_type', o.offer_type,
      'reward', o.reward,
      'currency_code', o.currency_code,
      'icon_url', o.icon_url,
      'destination_url', o.destination_url,
      'platform', o.platform,
      'estimated_time_minutes', o.estimated_time_minutes,
      'difficulty', o.difficulty,
      'category', o.category
    ) ORDER BY o.reward DESC)
    FROM offers o
    JOIN offer_providers p ON p.id = o.provider_id
    WHERE o.active = true
      AND p.enabled = true
      AND (o.start_date IS NULL OR now() >= o.start_date)
      AND (o.end_date IS NULL OR now() <= o.end_date)
      AND (p_offer_type = 'all' OR o.offer_type = p_offer_type)
      AND (p_platform = 'all' OR o.platform = 'all' OR o.platform = p_platform)
  ), '[]'::jsonb);
END;
$$;

REVOKE EXECUTE ON FUNCTION offer_list_available(text, text) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION offer_list_available(text, text) TO authenticated;

-- =============================================================
-- FUNCTION: offer_list_my_sessions (user-facing)
-- =============================================================
CREATE OR REPLACE FUNCTION offer_list_my_sessions(
  p_status text DEFAULT 'all',
  p_limit int DEFAULT 50,
  p_offset int DEFAULT 0
)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_user uuid := auth.uid();
BEGIN
  IF v_user IS NULL THEN
    RETURN '[]'::jsonb;
  END IF;

  RETURN COALESCE((
    SELECT jsonb_agg(jsonb_build_object(
      'id', s.id,
      'tracking_id', s.tracking_id,
      'provider_slug', s.provider_slug,
      'provider_offer_id', s.provider_offer_id,
      'offer_type', s.offer_type,
      'status', s.status,
      'reward', s.reward,
      'currency_code', s.currency_code,
      'provider_conversion_id', s.provider_conversion_id,
      'created_at', s.created_at,
      'completed_at', s.completed_at,
      'reversed_at', s.reversed_at,
      'offer_title', o.title,
      'offer_icon', o.icon_url
    ) ORDER BY s.created_at DESC)
    FROM offer_sessions s
    LEFT JOIN offers o ON o.id = s.offer_id
    WHERE s.user_id = v_user
      AND (p_status = 'all' OR s.status = p_status)
    LIMIT p_limit OFFSET p_offset
  ), '[]'::jsonb);
END;
$$;

REVOKE EXECUTE ON FUNCTION offer_list_my_sessions(text, int, int) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION offer_list_my_sessions(text, int, int) TO authenticated;

-- =============================================================
-- FUNCTION: offer_get_session (user-facing)
-- =============================================================
CREATE OR REPLACE FUNCTION offer_get_session(p_session_id uuid)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_user uuid := auth.uid();
  v_session offer_sessions%ROWTYPE;
  v_offer offers%ROWTYPE;
BEGIN
  IF v_user IS NULL THEN
    RETURN jsonb_build_object('error', 'Not authenticated');
  END IF;

  SELECT * INTO v_session FROM offer_sessions WHERE id = p_session_id AND user_id = v_user;
  IF NOT FOUND THEN
    RETURN jsonb_build_object('error', 'Session not found');
  END IF;

  SELECT * INTO v_offer FROM offers WHERE id = v_session.offer_id;

  RETURN jsonb_build_object(
    'id', v_session.id,
    'tracking_id', v_session.tracking_id,
    'provider_slug', v_session.provider_slug,
    'offer_type', v_session.offer_type,
    'status', v_session.status,
    'reward', v_session.reward,
    'currency_code', v_session.currency_code,
    'created_at', v_session.created_at,
    'completed_at', v_session.completed_at,
    'reversed_at', v_session.reversed_at,
    'metadata', v_session.metadata,
    'offer_title', v_offer.title,
    'offer_description', v_offer.description,
    'offer_requirements', v_offer.requirements,
    'offer_icon', v_offer.icon_url,
    'offer_platform', v_offer.platform,
    'estimated_time_minutes', v_offer.estimated_time_minutes,
    'difficulty', v_offer.difficulty
  );
END;
$$;

REVOKE EXECUTE ON FUNCTION offer_get_session(uuid) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION offer_get_session(uuid) TO authenticated;

-- =============================================================
-- FUNCTION: offer_process_conversion (service-role only)
-- Called by the offer-webhook edge function. NOT granted to anon/authenticated.
-- =============================================================
CREATE OR REPLACE FUNCTION offer_process_conversion(
  p_provider_slug text,
  p_tracking_id text,
  p_conversion_id text,
  p_reward numeric,
  p_revenue numeric DEFAULT 0,
  p_event_type text DEFAULT 'conversion',
  p_raw jsonb DEFAULT '{}'::jsonb
)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_provider offer_providers%ROWTYPE;
  v_session offer_sessions%ROWTYPE;
  v_profile profiles%ROWTYPE;
  v_tx_id uuid;
  v_final_reward numeric;
  v_conversion_exists boolean;
  v_ref text;
BEGIN
  -- Validate provider
  SELECT * INTO v_provider FROM offer_providers WHERE slug = p_provider_slug AND enabled = true;
  IF NOT FOUND THEN
    RETURN jsonb_build_object('status', 'rejected', 'reason', 'Provider not found or disabled');
  END IF;

  -- Find session by tracking_id
  SELECT * INTO v_session FROM offer_sessions WHERE tracking_id = p_tracking_id FOR UPDATE;
  IF NOT FOUND THEN
    RETURN jsonb_build_object('status', 'rejected', 'reason', 'Session not found for tracking_id');
  END IF;

  -- Check for duplicate conversion (idempotency)
  SELECT EXISTS(
    SELECT 1 FROM offer_conversions
    WHERE provider_id = v_provider.id
      AND provider_conversion_id = p_conversion_id
      AND event_type = p_event_type
  ) INTO v_conversion_exists;

  IF v_conversion_exists THEN
    -- Record as duplicate for audit, but don't credit
    INSERT INTO offer_conversions (
      session_id, user_id, provider_id, provider_conversion_id,
      event_type, reward, revenue, status, raw_payload
    ) VALUES (
      v_session.id, v_session.user_id, v_provider.id, p_conversion_id,
      p_event_type, p_reward, p_revenue, 'duplicate', p_raw
    ) ON CONFLICT (provider_id, provider_conversion_id, event_type) DO NOTHING;

    RETURN jsonb_build_object('status', 'duplicate', 'reason', 'Conversion already processed');
  END IF;

  -- Calculate final reward with provider margin
  v_final_reward := p_reward * (v_provider.reward_margin_percent / 100.0);

  IF p_event_type = 'conversion' THEN
    -- Don't process if session is already completed or reversed
    IF v_session.status IN ('completed', 'reversed') THEN
      INSERT INTO offer_conversions (
        session_id, user_id, provider_id, provider_conversion_id,
        event_type, reward, revenue, status, raw_payload
      ) VALUES (
        v_session.id, v_session.user_id, v_provider.id, p_conversion_id,
        p_event_type, v_final_reward, p_revenue, 'rejected', p_raw
      ) ON CONFLICT DO NOTHING;
      RETURN jsonb_build_object('status', 'rejected', 'reason', 'Session already ' || v_session.status);
    END IF;

    -- Lock profile for balance update
    SELECT * INTO v_profile FROM profiles WHERE id = v_session.user_id FOR UPDATE;
    IF NOT FOUND THEN
      RETURN jsonb_build_object('status', 'rejected', 'reason', 'User profile not found');
    END IF;

    -- Create idempotent ledger entry
    v_ref := 'offer:' || v_session.id::text;
    INSERT INTO transactions (
      user_id, type, amount, reference_type, reference_id, reference, description, status
    ) VALUES (
      v_session.user_id, 'offer_reward', v_final_reward,
      'offer_session', v_session.id::text, v_ref,
      'Offer Reward — ' || v_session.provider_slug, 'completed'
    ) ON CONFLICT (reference) DO NOTHING RETURNING id INTO v_tx_id;

    -- Only credit balance if the transaction was actually inserted (not a duplicate)
    IF v_tx_id IS NOT NULL THEN
      UPDATE profiles
      SET available_balance = available_balance + v_final_reward,
          total_earned = total_earned + v_final_reward
      WHERE id = v_session.user_id;
    END IF;

    -- Update session
    UPDATE offer_sessions
    SET status = 'completed',
        completed_at = now(),
        provider_conversion_id = p_conversion_id,
        revenue = p_revenue
    WHERE id = v_session.id;

    -- Record conversion
    INSERT INTO offer_conversions (
      session_id, user_id, provider_id, provider_conversion_id,
      event_type, reward, revenue, status, raw_payload
    ) VALUES (
      v_session.id, v_session.user_id, v_provider.id, p_conversion_id,
      'conversion', v_final_reward, p_revenue, 'processed', p_raw
    ) ON CONFLICT DO NOTHING;

    RETURN jsonb_build_object(
      'status', 'processed',
      'session_id', v_session.id,
      'reward', v_final_reward,
      'transaction_id', v_tx_id
    );

  ELSIF p_event_type = 'reversal' THEN
    -- Reversal: debit the balance, mark session reversed
    IF v_session.status != 'completed' THEN
      INSERT INTO offer_conversions (
        session_id, user_id, provider_id, provider_conversion_id,
        event_type, reward, revenue, status, raw_payload
      ) VALUES (
        v_session.id, v_session.user_id, v_provider.id, p_conversion_id,
        'reversal', v_final_reward, p_revenue, 'rejected', p_raw
      ) ON CONFLICT DO NOTHING;
      RETURN jsonb_build_object('status', 'rejected', 'reason', 'Session not in completed state');
    END IF;

    SELECT * INTO v_profile FROM profiles WHERE id = v_session.user_id FOR UPDATE;

    v_ref := 'offer_reversal:' || v_session.id::text;
    INSERT INTO transactions (
      user_id, type, amount, reference_type, reference_id, reference, description, status
    ) VALUES (
      v_session.user_id, 'offer_reversal', -v_final_reward,
      'offer_session', v_session.id::text, v_ref,
      'Offer Reversal — ' || v_session.provider_slug, 'reversed'
    ) ON CONFLICT (reference) DO NOTHING RETURNING id INTO v_tx_id;

    IF v_tx_id IS NOT NULL THEN
      UPDATE profiles
      SET available_balance = available_balance - v_final_reward,
          total_earned = total_earned - v_final_reward
      WHERE id = v_session.user_id;
    END IF;

    UPDATE offer_sessions
    SET status = 'reversed',
        reversed_at = now()
    WHERE id = v_session.id;

    INSERT INTO offer_conversions (
      session_id, user_id, provider_id, provider_conversion_id,
      event_type, reward, revenue, status, raw_payload
    ) VALUES (
      v_session.id, v_session.user_id, v_provider.id, p_conversion_id,
      'reversal', v_final_reward, p_revenue, 'processed', p_raw
    ) ON CONFLICT DO NOTHING;

    RETURN jsonb_build_object(
      'status', 'processed',
      'session_id', v_session.id,
      'reversed_reward', v_final_reward,
      'transaction_id', v_tx_id
    );

  ELSE
    RETURN jsonb_build_object('status', 'rejected', 'reason', 'Unknown event type');
  END IF;
END;
$$;

-- CRITICAL: Do NOT grant to anon or authenticated — service role only
REVOKE EXECUTE ON FUNCTION offer_process_conversion(text, text, text, numeric, numeric, text, jsonb) FROM PUBLIC;

-- =============================================================
-- FUNCTION: offer_admin_stats (admin-only)
-- =============================================================
CREATE OR REPLACE FUNCTION offer_admin_stats()
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_is_admin boolean;
BEGIN
  SELECT is_admin() INTO v_is_admin;
  IF NOT v_is_admin THEN
    RETURN jsonb_build_object('error', 'Unauthorized');
  END IF;

  RETURN jsonb_build_object(
    'total_clicks', (SELECT count(*) FROM offer_sessions),
    'started', (SELECT count(*) FROM offer_sessions WHERE status IN ('started','pending','completed')),
    'completed', (SELECT count(*) FROM offer_sessions WHERE status = 'completed'),
    'pending', (SELECT count(*) FROM offer_sessions WHERE status IN ('clicked','started','pending')),
    'reversed', (SELECT count(*) FROM offer_sessions WHERE status = 'reversed'),
    'rejected', (SELECT count(*) FROM offer_sessions WHERE status = 'rejected'),
    'total_rewards', (SELECT COALESCE(sum(reward), 0) FROM offer_sessions WHERE status = 'completed'),
    'total_revenue', (SELECT COALESCE(sum(revenue), 0) FROM offer_sessions WHERE status = 'completed'),
    'active_providers', (SELECT count(*) FROM offer_providers WHERE enabled = true),
    'total_providers', (SELECT count(*) FROM offer_providers),
    'total_offers', (SELECT count(*) FROM offers WHERE active = true)
  );
END;
$$;

REVOKE EXECUTE ON FUNCTION offer_admin_stats() FROM PUBLIC;
GRANT EXECUTE ON FUNCTION offer_admin_stats() TO authenticated;

-- =============================================================
-- FUNCTION: offer_admin_list_sessions (admin-only)
-- =============================================================
CREATE OR REPLACE FUNCTION offer_admin_list_sessions(
  p_provider_slug text DEFAULT NULL,
  p_offer_type text DEFAULT NULL,
  p_status text DEFAULT NULL,
  p_user_id uuid DEFAULT NULL,
  p_limit int DEFAULT 100,
  p_offset int DEFAULT 0
)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_is_admin boolean;
BEGIN
  SELECT is_admin() INTO v_is_admin;
  IF NOT v_is_admin THEN
    RETURN '[]'::jsonb;
  END IF;

  RETURN COALESCE((
    SELECT jsonb_agg(jsonb_build_object(
      'id', s.id,
      'user_id', s.user_id,
      'username', p.username,
      'email', p.email,
      'provider_slug', s.provider_slug,
      'provider_offer_id', s.provider_offer_id,
      'offer_type', s.offer_type,
      'status', s.status,
      'reward', s.reward,
      'revenue', s.revenue,
      'provider_conversion_id', s.provider_conversion_id,
      'tracking_id', s.tracking_id,
      'created_at', s.created_at,
      'completed_at', s.completed_at,
      'reversed_at', s.reversed_at,
      'offer_title', o.title
    ) ORDER BY s.created_at DESC)
    FROM offer_sessions s
    LEFT JOIN profiles p ON p.id = s.user_id
    LEFT JOIN offers o ON o.id = s.offer_id
    WHERE (p_provider_slug IS NULL OR s.provider_slug = p_provider_slug)
      AND (p_offer_type IS NULL OR s.offer_type = p_offer_type)
      AND (p_status IS NULL OR s.status = p_status)
      AND (p_user_id IS NULL OR s.user_id = p_user_id)
    LIMIT p_limit OFFSET p_offset
  ), '[]'::jsonb);
END;
$$;

REVOKE EXECUTE ON FUNCTION offer_admin_list_sessions(text, text, text, uuid, int, int) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION offer_admin_list_sessions(text, text, text, uuid, int, int) TO authenticated;

-- =============================================================
-- FUNCTION: offer_admin_list_providers (admin-only)
-- Returns provider configs WITHOUT secrets
-- =============================================================
CREATE OR REPLACE FUNCTION offer_admin_list_providers()
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_is_admin boolean;
BEGIN
  SELECT is_admin() INTO v_is_admin;
  IF NOT v_is_admin THEN
    RETURN '[]'::jsonb;
  END IF;

  RETURN COALESCE((
    SELECT jsonb_agg(jsonb_build_object(
      'id', p.id,
      'slug', p.slug,
      'display_name', p.display_name,
      'provider_type', p.provider_type,
      'enabled', p.enabled,
      'has_api_key', p.api_key_encrypted IS NOT NULL,
      'has_postback_secret', p.postback_secret_encrypted IS NOT NULL,
      'publisher_id', p.publisher_id,
      'postback_url', p.postback_url,
      'currency_code', p.currency_code,
      'reward_margin_percent', p.reward_margin_percent,
      'config', p.config,
      'created_at', p.created_at
    ) ORDER BY p.created_at)
    FROM offer_providers p
  ), '[]'::jsonb);
END;
$$;

REVOKE EXECUTE ON FUNCTION offer_admin_list_providers() FROM PUBLIC;
GRANT EXECUTE ON FUNCTION offer_admin_list_providers() TO authenticated;

-- =============================================================
-- FUNCTION: offer_admin_update_provider (admin-only)
-- =============================================================
CREATE OR REPLACE FUNCTION offer_admin_update_provider(
  p_provider_id uuid,
  p_enabled boolean DEFAULT NULL,
  p_display_name text DEFAULT NULL,
  p_publisher_id text DEFAULT NULL,
  p_reward_margin_percent numeric DEFAULT NULL,
  p_config jsonb DEFAULT NULL
)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_is_admin boolean;
  v_count int;
BEGIN
  SELECT is_admin() INTO v_is_admin;
  IF NOT v_is_admin THEN
    RETURN jsonb_build_object('error', 'Unauthorized');
  END IF;

  UPDATE offer_providers SET
    enabled = COALESCE(p_enabled, enabled),
    display_name = COALESCE(p_display_name, display_name),
    publisher_id = COALESCE(p_publisher_id, publisher_id),
    reward_margin_percent = COALESCE(p_reward_margin_percent, reward_margin_percent),
    config = COALESCE(p_config, config),
    updated_at = now()
  WHERE id = p_provider_id
  RETURNING 1 INTO v_count;

  IF v_count IS NULL THEN
    RETURN jsonb_build_object('error', 'Provider not found');
  END IF;

  RETURN jsonb_build_object('ok', true);
END;
$$;

REVOKE EXECUTE ON FUNCTION offer_admin_update_provider(uuid, boolean, text, text, numeric, jsonb) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION offer_admin_update_provider(uuid, boolean, text, text, numeric, jsonb) TO authenticated;

-- =============================================================
-- FUNCTION: offer_admin_set_provider_secret (admin-only)
-- Stores secrets encrypted with pgp_sym_encrypt
-- =============================================================
CREATE OR REPLACE FUNCTION offer_admin_set_provider_secret(
  p_provider_id uuid,
  p_secret_type text,
  p_secret_value text
)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_is_admin boolean;
  v_count int;
  v_encrypted text;
  v_key text;
BEGIN
  SELECT is_admin() INTO v_is_admin;
  IF NOT v_is_admin THEN
    RETURN jsonb_build_object('error', 'Unauthorized');
  END IF;

  -- Use a fixed encryption key derived from the project's service role
  -- In production, this should be a dedicated secret key
  v_key := current_setting('app.secret_key', true);
  IF v_key IS NULL OR v_key = '' THEN
    -- Fallback: use a deterministic key from the database superuser role
    v_key := 'goldclicks_offer_encryption_key_2024';
  END IF;

  v_encrypted := pgp_sym_encrypt(p_secret_value, v_key);

  IF p_secret_type = 'api_key' THEN
    UPDATE offer_providers SET
      api_key_encrypted = v_encrypted,
      updated_at = now()
    WHERE id = p_provider_id
    RETURNING 1 INTO v_count;
  ELSIF p_secret_type = 'postback_secret' THEN
    UPDATE offer_providers SET
      postback_secret_encrypted = v_encrypted,
      updated_at = now()
    WHERE id = p_provider_id
    RETURNING 1 INTO v_count;
  ELSE
    RETURN jsonb_build_object('error', 'Unknown secret type');
  END IF;

  IF v_count IS NULL THEN
    RETURN jsonb_build_object('error', 'Provider not found');
  END IF;

  RETURN jsonb_build_object('ok', true);
END;
$$;

REVOKE EXECUTE ON FUNCTION offer_admin_set_provider_secret(uuid, text, text) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION offer_admin_set_provider_secret(uuid, text, text) TO authenticated;

-- =============================================================
-- FUNCTION: offer_admin_create_provider (admin-only)
-- =============================================================
CREATE OR REPLACE FUNCTION offer_admin_create_provider(
  p_slug text,
  p_display_name text,
  p_provider_type text,
  p_publisher_id text DEFAULT '',
  p_postback_url text DEFAULT '',
  p_reward_margin_percent numeric DEFAULT 100,
  p_config jsonb DEFAULT '{}'::jsonb
)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_is_admin boolean;
  v_id uuid;
BEGIN
  SELECT is_admin() INTO v_is_admin;
  IF NOT v_is_admin THEN
    RETURN jsonb_build_object('error', 'Unauthorized');
  END IF;

  INSERT INTO offer_providers (
    slug, display_name, provider_type, publisher_id, postback_url,
    reward_margin_percent, config, enabled
  ) VALUES (
    p_slug, p_display_name, p_provider_type, p_publisher_id, p_postback_url,
    p_reward_margin_percent, p_config, false
  ) RETURNING id INTO v_id;

  RETURN jsonb_build_object('ok', true, 'id', v_id);
END;
$$;

REVOKE EXECUTE ON FUNCTION offer_admin_create_provider(text, text, text, text, text, numeric, jsonb) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION offer_admin_create_provider(text, text, text, text, text, numeric, jsonb) TO authenticated;

-- =============================================================
-- FUNCTION: offer_get_postback_secret (service-role only)
-- Used by edge function to verify provider signatures
-- =============================================================
CREATE OR REPLACE FUNCTION offer_get_postback_secret(
  p_provider_slug text,
  p_secret_type text
)
RETURNS text
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_encrypted text;
  v_decrypted text;
  v_key text;
BEGIN
  IF p_secret_type = 'api_key' THEN
    SELECT api_key_encrypted INTO v_encrypted FROM offer_providers WHERE slug = p_provider_slug;
  ELSIF p_secret_type = 'postback_secret' THEN
    SELECT postback_secret_encrypted INTO v_encrypted FROM offer_providers WHERE slug = p_provider_slug;
  ELSE
    RETURN NULL;
  END IF;

  IF v_encrypted IS NULL THEN
    RETURN NULL;
  END IF;

  v_key := current_setting('app.secret_key', true);
  IF v_key IS NULL OR v_key = '' THEN
    v_key := 'goldclicks_offer_encryption_key_2024';
  END IF;

  v_decrypted := pgp_sym_decrypt(v_encrypted::bytea, v_key);
  RETURN v_decrypted;
END;
$$;

REVOKE EXECUTE ON FUNCTION offer_get_postback_secret(text, text) FROM PUBLIC;
-- NOT granted to anon or authenticated — service role only